{{- if .Values.serviceAccount.create -}}
  {{- template "common-frontend.serviceaccount" (list . "terkep-test.serviceaccount") -}}
{{- end -}}
{{- define "terkep-test.serviceaccount" -}}
## Define overrides for your Service Account resource here
{{- end -}}