/**
 * @file This is a generated file. Please do not modify it manually.
 * All manual changes will be erased on the next run of the generator.
 * Generated by @eing/schematics.
 */

/**
 * The app's version according to the root package.json.
 */
export const version = '0.0.0';
