# Default values for terkep-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: e-ing/terkep-test
  tag: stable
  pullPolicy: Always

# environment.json values
env:
  production: false

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 999

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  certManager: false
  hostname: terkep-test.local
  annotations: {}

persistence:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}
